# Generated by Django 4.0.6 on 2024-04-22 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import galleryfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo2', models.ImageField(upload_to='my_images2', verbose_name='Image2')),
            ],
        ),
        migrations.CreateModel(
            name='MyImage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='my_images1', verbose_name='Image1')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='MyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album1', galleryfield.fields.GalleryField(target_model='demo_multiple_fields_1_model.MyImage1', verbose_name='My photos')),
                ('album2', galleryfield.fields.GalleryField(target_model='demo_multiple_fields_1_model.MyImage2', verbose_name='My photos2')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
