# Generated by Django 3.2.5 on 2021-07-28 15:30

from django.db import migrations, models
import gallery.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', gallery.fields.GalleryField(blank=True, null=True)),
            ],
        ),
    ]
